# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from f_usuarios import Ui_usuarios
from f_control import Ui_control
from f_ventas import Ui_ventas
from f_ing_din import Ui_idin
from f_ret_din import Ui_rdin


class Ui_MainWindow(object):

    def usuarios(self):
        self.f_usuarios = QtWidgets.QWidget()
        self.ui = Ui_usuarios()
        self.ui.setupUi(self.f_usuarios)
        
        self.mdiArea.addSubWindow(self.f_usuarios)
        if self.f_usuarios == 0:

            self.f_usuarios.show()
        else:
            self.f_usuarios.activateWindow()

    def controlstock(self):
        self.f_control = QtWidgets.QWidget()
        self.ui = Ui_control()
        self.ui.setupUi(self.f_control)
        self.mdiArea.addSubWindow(self.f_control)
        self.f_control.show()

    def ventas(self):
        self.f_ventas = QtWidgets.QWidget()
        self.ui = Ui_ventas()
        self.ui.setupUi(self.f_ventas)
        self.mdiArea.addSubWindow(self.f_ventas)
        self.f_ventas.show()

    def retirodin(self):
        self.f_ret_din = QtWidgets.QWidget()
        self.ui = Ui_rdin()
        self.ui.setupUi(self.f_ret_din)
        self.mdiArea.addSubWindow(self.f_ret_din)
        self.f_ret_din.show()
        self.f_ret_din.setWindowTitle('Retiro de dinero')

    def ingresodin(self):
        self.f_ing_din = QtWidgets.QWidget()
        self.ui = Ui_idin()
        self.ui.setupUi(self.f_ing_din)
        self.mdiArea.addSubWindow(self.f_ing_din)
        self.f_ing_din.show()
        self.f_ing_din.setWindowTitle('Ingreso de dinero')

    def salir(self):
        exit()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(880, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/icon_qpyme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagenes/icons8-create-document-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)

        self.pushButton.clicked.connect(self.ventas)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/icons8-request-money-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)

        self.pushButton_2.clicked.connect(self.ingresodin)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/icons8-initiate-money-transfer-50.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.retirodin)

        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imagenes/icons8-inspection-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 25))
        self.menubar.setObjectName("menubar")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        self.menuTurno = QtWidgets.QMenu(self.menuInicio)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("imagenes/icons8-contact-details-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuTurno.setIcon(icon5)
        self.menuTurno.setObjectName("menuTurno")
        self.menuMovimientos = QtWidgets.QMenu(self.menubar)
        self.menuMovimientos.setObjectName("menuMovimientos")
        self.menuAdministracion = QtWidgets.QMenu(self.menubar)
        self.menuAdministracion.setObjectName("menuAdministracion")
        self.menuBase_de_datos = QtWidgets.QMenu(self.menuAdministracion)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("imagenes/icons8-work-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBase_de_datos.setIcon(icon6)
        self.menuBase_de_datos.setObjectName("menuBase_de_datos")
        self.menuReportes = QtWidgets.QMenu(self.menuAdministracion)
        self.menuReportes.setObjectName("menuReportes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIngreso_dinero = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/icons8-request-money-50.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.actionIngreso_dinero.setIcon(icon2)
        self.actionIngreso_dinero.setObjectName("actionIngreso_dinero")
        self.actionIngreso_dinero.triggered.connect(self.ingresodin)
        self.actionSalida_dinero = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/icons8-initiate-money-transfer-50.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.actionSalida_dinero.setIcon(icon3)
        self.actionSalida_dinero.setObjectName("actionSalida_dinero")
        self.actionSalida_dinero.triggered.connect(self.retirodin)

        self.actionSalir = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("imagenes/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon7)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSalir.triggered.connect(self.salir)
        self.actionUsuarios_2 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("imagenes/icons8-badge-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUsuarios_2.setIcon(icon8)
        self.actionUsuarios_2.setObjectName("actionUsuarios_2")

        self.actionUsuarios_2.triggered.connect(self.usuarios)

        self.actionControl_Stock = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("imagenes/icons8-questionnaire-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionControl_Stock.setIcon(icon9)
        self.actionControl_Stock.setObjectName("actionControl_Stock")

        self.actionControl_Stock.triggered.connect(self.controlstock)

        self.actionCompactar = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("imagenes/icons8-console-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompactar.setIcon(icon10)
        self.actionCompactar.setObjectName("actionCompactar")
        self.actionExportar = QtWidgets.QAction(MainWindow)
        self.actionExportar.setIcon(icon10)
        self.actionExportar.setObjectName("actionExportar")
        self.actionImportar = QtWidgets.QAction(MainWindow)
        self.actionImportar.setIcon(icon10)
        self.actionImportar.setObjectName("actionImportar")
        self.actionVenta_del_dia = QtWidgets.QAction(MainWindow)
        self.actionVenta_del_dia.setIcon(icon4)
        self.actionVenta_del_dia.setObjectName("actionVenta_del_dia")
        self.actionInicio_de_turno = QtWidgets.QAction(MainWindow)
        self.actionInicio_de_turno.setObjectName("actionInicio_de_turno")
        self.actionCierre_de_turno = QtWidgets.QAction(MainWindow)
        self.actionCierre_de_turno.setObjectName("actionCierre_de_turno")
        self.actionInicio_de_turno_2 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("imagenes/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInicio_de_turno_2.setIcon(icon11)
        self.actionInicio_de_turno_2.setObjectName("actionInicio_de_turno_2")
        self.actionCierre_de_turno_2 = QtWidgets.QAction(MainWindow)
        self.actionCierre_de_turno_2.setIcon(icon7)
        self.actionCierre_de_turno_2.setObjectName("actionCierre_de_turno_2")
        self.actionSalir_2 = QtWidgets.QAction(MainWindow)
        self.actionSalir_2.setIcon(icon7)
        self.actionSalir_2.setObjectName("actionSalir_2")

        self.actionSalir_2.triggered.connect(self.salir)

        self.menuTurno.addAction(self.actionInicio_de_turno_2)
        self.menuTurno.addAction(self.actionCierre_de_turno_2)
        self.menuInicio.addAction(self.menuTurno.menuAction())
        self.menuInicio.addAction(self.actionSalir_2)
        self.menuMovimientos.addAction(self.actionIngreso_dinero)
        self.menuMovimientos.addAction(self.actionSalida_dinero)
        self.menuBase_de_datos.addAction(self.actionCompactar)
        self.menuBase_de_datos.addAction(self.actionExportar)
        self.menuBase_de_datos.addAction(self.actionImportar)
        self.menuReportes.addAction(self.actionVenta_del_dia)
        self.menuAdministracion.addAction(self.actionUsuarios_2)
        self.menuAdministracion.addSeparator()
        self.menuAdministracion.addAction(self.actionControl_Stock)
        self.menuAdministracion.addSeparator()
        self.menuAdministracion.addAction(self.menuBase_de_datos.menuAction())
        self.menuAdministracion.addSeparator()
        self.menuAdministracion.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuInicio.menuAction())
        self.menubar.addAction(self.menuMovimientos.menuAction())
        self.menubar.addAction(self.menuAdministracion.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QPyme"))
        self.menuInicio.setTitle(_translate("MainWindow", "Inicio"))
        self.menuTurno.setTitle(_translate("MainWindow", "Turno"))
        self.menuMovimientos.setTitle(_translate("MainWindow", "Movimientos"))
        self.menuAdministracion.setTitle(_translate("MainWindow", "Administracion"))
        self.menuBase_de_datos.setTitle(_translate("MainWindow", "Base de datos"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.actionIngreso_dinero.setText(_translate("MainWindow", "Ingreso dinero"))
        self.actionSalida_dinero.setText(_translate("MainWindow", "Salida dinero"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionUsuarios_2.setText(_translate("MainWindow", "Usuarios"))
        self.actionControl_Stock.setText(_translate("MainWindow", "Control Stock"))
        self.actionCompactar.setText(_translate("MainWindow", "Compactar"))
        self.actionExportar.setText(_translate("MainWindow", "Exportar"))
        self.actionImportar.setText(_translate("MainWindow", "Importar"))
        self.actionVenta_del_dia.setText(_translate("MainWindow", "Venta del dia"))
        self.actionInicio_de_turno.setText(_translate("MainWindow", "Inicio de turno"))
        self.actionCierre_de_turno.setText(_translate("MainWindow", "Cierre de turno"))
        self.actionInicio_de_turno_2.setText(_translate("MainWindow", "Inicio de turno"))
        self.actionCierre_de_turno_2.setText(_translate("MainWindow", "Cierre de turno"))
        self.actionSalir_2.setText(_translate("MainWindow", "Salir"))
